namespace Transaction.repository.Queries
{
    public class TransactionQueries
    {
        public static string GetAll => @"SELECT ACCOUNTID, TRANSACTIONID, TRANSACTIONAMOUNT, TRANSACTIONCURRENCYCODE, LOCALHOUR, TRANSACTIONSCENARIO, TRANSACTIONTYPE, TRANSACTIONIPADDRESS, IPSTATE, IPPOSTALCODE, IPCOUNTRY, ISPROXYIP, BROWSERLANGUAGE, PAYMENTINSTRUMENTTYPE, CARDTYPE, PAYMENTBILLINGPOSTALCODE, PAYMENTBILLINGSTATE, PAYMENTBILLINGCOUNTRYCODE, SHIPPINGPOSTALCODE, SHIPPINGSTATE, SHIPPINGCOUNTRY, CVVVERIFYRESULT, DIGITALITEMCOUNT, PHYSICALITEMCOUNT, TRANSACTIONDATETIME FROM EDUARDO.TRANSACTION";

        public static string GetById => @"SELECT ACCOUNTID, TRANSACTIONID, TRANSACTIONAMOUNT, TRANSACTIONCURRENCYCODE, LOCALHOUR, TRANSACTIONSCENARIO, TRANSACTIONTYPE, TRANSACTIONIPADDRESS, IPSTATE, IPPOSTALCODE, IPCOUNTRY, ISPROXYIP, BROWSERLANGUAGE, PAYMENTINSTRUMENTTYPE, CARDTYPE, PAYMENTBILLINGPOSTALCODE, PAYMENTBILLINGSTATE, PAYMENTBILLINGCOUNTRYCODE, SHIPPINGPOSTALCODE, SHIPPINGSTATE, SHIPPINGCOUNTRY, CVVVERIFYRESULT, DIGITALITEMCOUNT, PHYSICALITEMCOUNT, TRANSACTIONDATETIME FROM EDUARDO.TRANSACTION WHERE TRANSACTIONID = :Id ";

        public static string Add =>
            @"INSERT INTO EDUARDO.TRANSACTION (ACCOUNTID,TRANSACTIONID,TRANSACTIONAMOUNT,TRANSACTIONCURRENCYCODE,LOCALHOUR,TRANSACTIONSCENARIO,TRANSACTIONTYPE,TRANSACTIONIPADDRESS,IPSTATE,IPPOSTALCODE,IPCOUNTRY,ISPROXYIP,BROWSERLANGUAGE,PAYMENTINSTRUMENTTYPE,CARDTYPE,PAYMENTBILLINGPOSTALCODE,PAYMENTBILLINGSTATE,PAYMENTBILLINGCOUNTRYCODE,SHIPPINGPOSTALCODE,SHIPPINGSTATE,SHIPPINGCOUNTRY,CVVVERIFYRESULT,DIGITALITEMCOUNT,PHYSICALITEMCOUNT,TRANSACTIONDATETIME) 
            VALUES 
            (:ACCOUNTID,:TRANSACTIONID,:TRANSACTIONAMOUNT,:TRANSACTIONCURRENCYCODE,:LOCALHOUR,:TRANSACTIONSCENARIO,:TRANSACTIONTYPE,:TRANSACTIONIPADDRESS,:IPSTATE,:IPPOSTALCODE,:IPCOUNTRY,:ISPROXYIP,:BROWSERLANGUAGE,:PAYMENTINSTRUMENTTYPE,:CARDTYPE,:PAYMENTBILLINGPOSTALCODE,:PAYMENTBILLINGSTATE,:PAYMENTBILLINGCOUNTRYCODE,:SHIPPINGPOSTALCODE,:SHIPPINGSTATE,:SHIPPINGCOUNTRY,:CVVVERIFYRESULT,:DIGITALITEMCOUNT,:PHYSICALITEMCOUNT,:TRANSACTIONDATETIME)
            ";

        public static string Update =>
            @"UPDATE EDUARDO.TRANSACTION SET
                TRANSACTIONAMOUNT = :TRANSACTIONAMOUNT, 
                TRANSACTIONCURRENCYCODE = :TRANSACTIONCURRENCYCODE, 
                LOCALHOUR = :LOCALHOUR, 
                TRANSACTIONSCENARIO = :TRANSACTIONSCENARIO, 
                TRANSACTIONTYPE = :TRANSACTIONTYPE, 
                TRANSACTIONIPADDRESS = :TRANSACTIONIPADDRESS, 
                IPSTATE = :IPSTATE,
                IPPOSTALCODE = :IPPOSTALCODE, 
                IPCOUNTRY = :IPCOUNTRY, 
                ISPROXYIP = :ISPROXYIP, 
                BROWSERLANGUAGE = :BROWSERLANGUAGE, 
                PAYMENTINSTRUMENTTYPE = :PAYMENTINSTRUMENTTYPE, 
                CARDTYPE = :CARDTYPE, 
                PAYMENTBILLINGPOSTALCODE = :PAYMENTBILLINGPOSTALCODE, 
                PAYMENTBILLINGSTATE = :PAYMENTBILLINGSTATE, 
                PAYMENTBILLINGCOUNTRYCODE = :PAYMENTBILLINGCOUNTRYCODE, 
                SHIPPINGPOSTALCODE = :SHIPPINGPOSTALCODE, 
                SHIPPINGSTATE = :SHIPPINGSTATE, 
                SHIPPINGCOUNTRY = :SHIPPINGCOUNTRY, 
                CVVVERIFYRESULT = :CVVVERIFYRESULT, 
                DIGITALITEMCOUNT = :DIGITALITEMCOUNT, 
                PHYSICALITEMCOUNT = :PHYSICALITEMCOUNT, 
                TRANSACTIONDATETIME = :TRANSACTIONDATETIME
            WHERE ACCOUNTID = :ACCOUNTID 
            AND TRANSACTIONID = :TRANSACTIONID ";

        public static string Delete => @"DELETE FROM EDUARDO.TRANSACTION WHERE TRANSACTIONID = :Id ";
    }
}
